//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetailsApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EMPLOYEE
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage="Required")]
        [MaxLength(12)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Required")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Phone number")]
        [MinLength(10,ErrorMessage ="Mobile number should be 10 digit")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "Required")]
        [DisplayFormat( DataFormatString = "{0:dd/MM/yyyy}")] 
        public Nullable<System.DateTime> DOB { get; set; }
       
    }
}
